name=STUC
version=0.2.0
author=Tobias Knauss <tobias.knauss@web.de>
maintainer=Tobias Knauss <tobias.knauss@web.de>
sentence=Sir Toby's Universal Communication Protocol
paragraph=Universal communication protocol for command and data exchange between microcontrollers and/or computers.
category=Communication
url=https://github.com/TobiasKnauss/ArduinoLib_STUC
architectures=*
