X(FAIL_STUC_Message_CommandIdInvalid        )
X(FAIL_STUC_Message_MessageIdInvalid        )
X(FAIL_STUC_Message_NotFound                )
X(FAIL_STUC_Message_OwnDeviceIdWrong        )
X(FAIL_STUC_Message_RemoteDeviceIdInvalid   )
X(FAIL_STUC_Message_ResultWrong             ) 
X(FAIL_STUC_Message_TimestampInvalid        )
