X(FAIL_UCOP_Message_CommandIdInvalid        )
X(FAIL_UCOP_Message_MessageIdInvalid        )
X(FAIL_UCOP_Message_NotFound                )
X(FAIL_UCOP_Message_OwnDeviceIdWrong        )
X(FAIL_UCOP_Message_RemoteDeviceIdInvalid   )
X(FAIL_UCOP_Message_ResultWrong             ) 
X(FAIL_UCOP_Message_TimestampInvalid        )
